apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-cicd-test
  labels:
    app: cicd-demo-1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-demo-1

  template:
    metadata:
      labels:
        app: cicd-demo-1
    spec:
      containers:
        - name: cicd-demo-1
          image: DOCKER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1