apiVersion: v1
kind: Service
metadata:
  name: github-cicd-demo-service
  labels:
    app: cicd-demo
spec:
  selector:
    app: cicd-demo

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer