apiVersion: v1
kind: Service
metadata:
  name: github-cicd-test-service
  labels:
    app: cicd-demo-1
spec:
  selector:
    app: cicd-demo-1

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer