apiVersion: v1
kind: Service
metadata:
  name: developeriq-ingestor-service
  namespace: developeriq
  labels:
    app: developeriq
spec:
  selector:
    app: developeriq

  ports:
    - port: 9090
      targetPort: 9090

  type: LoadBalancer